#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# Set sane defaults for Cask
export HOMEBREW_CASK_OPTS="--appdir=/Applications"

# Some basic defaults for Mac
export ARCHFLAGS="-arch x86_64"
# Ensure user bins take precedence
export PATH=/usr/local/bin:$PATH

# Python Python Python
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

# Set up GO
if [[ ! -d "$HOME/go" ]]; then
  mkdir $HOME/go
fi
export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin